services:

  astro:
    build: .
    container_name: astro-landing

    restart: unless-stopped

    env_file:
      - .env

    expose:
      - "4321"

  nginx:
    image: nginx:alpine
    container_name: astro-nginx

    restart: unless-stopped

    depends_on:
      - astro

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/nginx/certs:ro