services:
  astro:
    build: .
    container_name: astro-landing

    restart: unless-stopped

    env_file:
      - .env

    environment:
      HOST: 0.0.0.0
      PORT: 4321

    ports:
      - "80:4321"